---
# tasks file for VM Deployment

#############################################
#              AWX DEPLOY                   #
#############################################

- name: Notify Deployment begin
  slack:
    token: "{{ slack_token }}"
    msg: "AWX VM Deployment has begun. Your VM will be ready soon and its name will be {{ vm_name }} with specs - RAM: {{mem}} CPU: {{cpus}}"
    channel: '#general'

- name: Get VM disks
  command: "ls {{ vm_location }}"
  register: disks
  changed_when: "disks.rc != 0"
  become: yes

- name: Create a small VM disk
  become: yes
  command: >
           virt-builder --format qcow2 centos-7.6
           -o {{ vm_location }}/{{ vm_name }}.{{ file_type }}
           --root-password password:{{ root_pass }}
  when: vm_name not in disks.stdout

- name: Send Disk Created Notification  
  slack:
    token: "{{ slack_token }}"
    msg: "VM Disk successfully created! "
    channel: '#general'

- name: Get list of all VMs
  become: yes
  virt:
    command: "list_vms"
  register: vms

- name: Deploy VM
  become: yes
  command: >
           virt-install --import --name {{ vm_name }}
           --memory {{ mem }} --vcpus {{ cpus }}
           --disk {{ vm_location }}/{{ vm_name }}.{{ file_type }}
           --noautoconsole --os-variant {{ os_type }}
  when: vm_name not in vms

- name: Sleep for 30 seconds.
  shell: sleep 30

- name: Get VM IP
  become: yes
  shell: virsh domifaddr {{ vm_name }} |  awk '{print $4}' | tail -n 2 | head -n 1 | cut -d '/' -f 1
  register: ip

- name: Save VM IP
  become: yes
  set_fact:
    vm_ip: "{{ ip.stdout }}"

- name: Send VM IP
  slack:
    token: "{{ slack_token }}"
    msg: "VM Deployment was completed. VM IP address is - {{ vm_ip }}"
    channel: '#general'
