---
# tasks file for roles/testing

- name: Generate random string for VM name
  command: openssl rand -base64 3
  register: result
  tags:
    - small
    - large
    - XL

- name: Factor random
  set_fact:
    rand_gb_var: "{{ result.stdout }}"
  tags:
    - small
    - large
    - XL

- name: Get VM disks
  command: "ls {{ vm_location }}"
  register: disks
  changed_when: "disks.rc != 0"
  tags:
   - small
   - large
   - XL

- name: Create a small VM disk
  command: >
           virt-builder --format qcow2 centos-7.6
           -o {{ vm_location }}/{{ guests.small.name }}.{{ guests.small.file_type }}
           --root-password password:{{ root_pass }}
  when: guests.small.name not in disks.stdout
  tags:
    - small

- name: Get list of all VMs
  virt:
    command: "list_vms"
  register: vms
  tags:
    - small
    - large
    - XL

- name: Creating a small VM
  command: >
           virt-install --import --name {{ guests.small.name }}
           --memory {{ guests.small.mem }} --vcpus {{ guests.small.cpus }}
           --disk {{ vm_location }}/{{ guests.small.name }}.{{ guests.small.file_type }}
           --noautoconsole --os-variant {{ guests.small.os_type }}
  when: guests.small.name not in vms
  tags:
    - small
