---
# defaults file for roles/main

common:
 - git
 - vim-enchanced
 - htop
 - nano
 - zip
 - unzip
 - wget
 - net-tools

kvm:
 - qemu-kvm
 - qemu-img
 - virt-manager
 - libvirt
 - libvirt-python
 - libvirt-client
 - virt-install
 - virt-viewer
 - bridge-utils
 - "@X Window System"
 - xorg-x11-xauth
 - xorg-x11-fonts-*
 - xorg-x11-utils

docker:
  gpg_key: "https://download.docker.com/linux/centos/gpg"
  repo_url: "https://download.docker.com/linux/centos/docker-ce.repo"
  repo_path: "/etc/yum.repos.d/docker-ce.repo"
  packages:
    - "docker-ce"
    - "device-mapper-persistent-data"
    - "lvm2"
    - "python-setuptools"
    - "libselinux-python"
  pip:
    - "docker"
