---
# defaults file for roles/main

common:
 - git
 - htop
 - nano
 - zip
 - unzip
 - wget
 - net-tools
 - iptables-services

kvm:
 - qemu-kvm
 - qemu-img
 - virt-manager
 - libvirt
 - libvirt-python
 - libvirt-client
 - virt-install
 - virt-viewer
 - bridge-utils
 - "@X Window System"
 - xorg-x11-xauth
 - xorg-x11-fonts-*
 - xorg-x11-utils
 - guestfish

docker:
  packages:
    - "docker-ce"
    - "device-mapper-persistent-data"
    - "lvm2"
    - "python-setuptools"
    - "libselinux-python"
  pip:
    - "docker"
