---
# tasks file for roles/main

- name: update all packages
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: install epel-release
  yum:
    name: epel-release
    state: present

- name: install pre-defined packages / system wise
  yum: 
    name: "{{ common }}"
    state: "installed"
  with_items: "{{ common }}"
  
- name: install KVM packages and KVM customize
  yum: 
    name: "{{ kvm }}"
    state: "installed"
  with_items: "{{ kvm }}"

- name: add docker-ce-stable repo
  yum_repository:
    name: docker-ce-stable
    description: docker-ce stable repo
    file: docker-ce-stable
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: Install Docker Pakages
  yum:
    name: "{{ docker.packages }}"
    state: "installed"
  with_items: "{{ docker.packages }}"

- name: Disable selinux
  lineinfile:
    destfile: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'

- name: disabled and mask firewalld
  systemd:
    name: firewalld
    enabled: no
    state: stopped
    masked: yes

- name: start / enable iptables
  systemd:
    name: iptables
    enabled: yes
    masked: no
    state: started

- name: start / enable docker
  systemd:
    name: docker
    enabled: yes
    state: started
    masked: no

- name: start / enable libvirtd
  systemd:
    name: libvirtd
    enabled: yes
    state: started
    masked: no

- name: just force systemd to reread configs
  systemd: daemon_reload=yes
