---
# tasks file for roles/main

- name: update all packages
  yum:
  name: *
  state: latest
  update_cache: yes

- name: install epel-release
  yum:
  name: epel-release
  state: present

- name: install pre-defined packages / system wise
  yum: {{ common }}
  state: installed
  with_items: {{ common }}

- name: install KVM packages and KVM customize
  yum: {{ kvm }}
  state: installed
  with_items: {{ kvm }}

- name: disabled and mask firewalld
  systemd:
    name: firewalld
    enabled: no
    state: stopped
    masked: yes

- name: just force systemd to reread configs
  systemd: daemon_reload=yes

- name: make sure libvitd is started and enabled
  systemd:
    name: libvirtd
    enabled: yes
    state: started
    masked: no

- name: Disable selinux
  lineinfile:
    destfile: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'

- name: add the gpg key for the docker repo
  rpm_key:
  key: {{ docker.gpg_key }}
  state: present

- name: add docker repo from the remote url
  get_url:
  url: {{ docker.repo_url }}
  dest: {{ docker.repo_path }}
  mode: 0644


- name: install the docker packages
  yum:
  name: {{ docker.packages }}
  state: installed
  update_cache: yes
  with_items: {{ docker.packages }}

- name: install pip
 easy_install:
 name: pip
 state: latest

- name: install the python packages
  pip:
  name: {{ docker.pip }}
  with_items: {{ docker.pip }}

- name: make sure docker is started and enabled
  systemd:
    name: docker
    enabled: yes
    state: started
    masked: no
